import { eq } from 'drizzle-orm';
import { threads, projects, type NewThread } from '../../database/schema';
import { useDB } from '../../utils/db';

/**
 * POST /api/threads
 * Create a new thread within a project
 * 
 * Body: {
 *   projectId: string (UUID),
 *   title?: string,
 *   modeHint?: string ('chat' | 'code' | 'auto')
 * }
 */
export default defineEventHandler(async (event) => {
  const db = useDB();
  const body = await readBody(event);
  
  // Validate required fields
  if (!body.projectId) {
    throw createError({
      statusCode: 400,
      statusMessage: 'Missing required field: projectId',
    });
  }
  
  try {
    // First, fetch the project to get the memarch_project_id
    const [project] = await db
      .select()
      .from(projects)
      .where(eq(projects.id, body.projectId))
      .limit(1);
    
    if (!project) {
      throw createError({
        statusCode: 404,
        statusMessage: 'Project not found',
      });
    }
    
    // Generate the thread UUID (will be auto-generated by DB, but we need it for memarch_external_ref)
    // We'll use a crypto.randomUUID() to pre-generate it
    const threadId = crypto.randomUUID();
    
    // Build the memarch_external_ref: "<memarch_project_id>:thread:<thread_uuid>"
    const memarchExternalRef = `${project.memarchProjectId}:thread:${threadId}`;
    
    const newThread: NewThread = {
      id: threadId,
      projectId: body.projectId,
      title: body.title || 'New chat',
      modeHint: body.modeHint || null,
      memarchExternalRef,
      isArchived: false,
      isPinned: false,
    };
    
    const [createdThread] = await db
      .insert(threads)
      .values(newThread)
      .returning();
    
    return {
      success: true,
      data: createdThread,
    };
  } catch (error: any) {
    console.error('Error creating thread:', error);
    
    // If it's already a createError, re-throw it
    if (error.statusCode) {
      throw error;
    }
    
    throw createError({
      statusCode: 500,
      statusMessage: 'Failed to create thread',
    });
  }
});
